### ISSUE TITLE
Update GSA Roadmap

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#100]
## Summary

Convene a small working group of Digital Council members to revise and update the [Roadmap for GSA's Digital Future](https://docs.google.com/document/d/1h-aC377wu2TOUvE8aFD7_ilR4MwcEce1wvbHyPavK0U/edit#heading=h.xief23a14tjm) to reflect 2021 accomplishments and 2022 priorities

## Checklist

- [x] Call for volunteers/contributors
- [x] schedule first working session
- [x] incorporate feedback and send out an updated version
- [x] schedule second working session 
- [x] socialize w/broader council for buy-in 
- [x] incorporate any final feedback
- [x] finalize 2022 roadmap
- [x] share w/Exec Board for their approval
- [x] Reissue roadmap

**Comment by RachelF** [comment]
Met w/Lashelle C today and she is reviewing to identify priorities and points that need clarification.
Plan is to rework the document into a full plan (no more appendix); document all the work we've accomplished so far, focus on work in progress, and time-box all future work.

**Comment by RachelF** [comment]
Shared draft with DC on 1/11; council members have until 1/18 to review, comment, and provide feedback

**Comment by RachelF** [comment]
DC received approval from the Board on 2/17 to proceed w/the new roadmap.

**Comment by RachelF** [comment]
Shared Roadmap w/Digital CoP in March 2022 newsletter.
