### ISSUE TITLE
Assign "lane managers" or "Service Managers" and ensure personas and journeys exist for GSA services

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#12]
## Goal & context

Source: 4th bullet in [Roadmap document](https://docs.google.com/document/d/1XjFGM-bN7lOLtWMDxrQbR9q6lG5iDsgYf_Z2E1yIyu8/edit?ts=602d4452#)

## Tasks

* [ ] identify or create a "source" list of GSA Services
* [ ] identify or create a "source" list of Behaviors/Needs
* [ ] identify or create a "source" list of Personas (have Behaviors/Needs)
* [ ] based on the list of Services, identity or create Service Models for each. 
  * [ ] Prioritize the ordering

---

Assuming user-centered design,
we start with a User.

Users can be grouped into Personas, as an abstraction to design around.

Each Persona has needs that can be expressed as Use Cases, or User Stories.

The delivery of services or products to meet those needs can be expressed as a Journey Map, Journey Blueprint, Service Blueprint, Sequence Diagram, or similar artifact.

**Comment by RachelF** [comment]
The DigCouncil has done some work to identify existing personas from across GSA; see https://docs.google.com/spreadsheets/d/1AGWNun9-8WCVFnkTR7024C-fCRVUy6-XkElUM9kDqQY/edit#gid=0

**Comment by ryanwoldatwork** [comment]
Thanks @RachelF - the list of personas is good. I'd like to see the "Primary Needs" delineated as data, in order to group them across Roles.   (The Personas are closely tied to Roles and Titles, but I prefer Personas to be grouped by behavior and need, which can be reassigned between roles).

This story needs stronger grounding.
Having assigned managers for Services make sense under some conditions, and I'll take it upon myself to write that up. I'm informing this based on my experience with CX CAP Goal work, where cross-agency journeys might be orchestrated by many teams, departments, or agencies - but a point of contact is assigned the responsibilities of reporting on and planning improvements to existing, defined Services.

**Comment by ryanwoldatwork** [comment]
![Screen Shot 2021-09-29 at 10 33 37 PM](https://user-images.githubusercontent.com/64987852/135393187-c0902648-7cfd-4bcd-b71f-c50868d6a0fe.png)

source: https://www.gsa.gov/cdnstatic/CC042452_Report_GSA%20Progress%20in%20Implementing%2021st%20Century%20IDEA%202019%20(2)%20(1).pdf

**Comment by anatecture** [comment]
This story is too broad and requires re-scope. Suggest that the work in website manager definition and PD updates led by @gailsprinkle and @monicas-d will add shape in near future. Closing this issue for now.
