### ISSUE TITLE
Incorporate WebMod plan into Council project plan

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#301]
## Summary

Incorporate specific webmod tasks/deliverables into the Council project plan.

## Additional context and links

[GSA Web Modernization Implementation Plan](https://docs.google.com/document/d/1nbHbdd8dKKA4rcUWBmnzfKcMsXKGWDMUHlrDALb9Gy8/edit#)

## Checklist

- [ ] Review plan and validate status of each task (keep or not, done or not)
- [ ] Document completed work
- [ ] Appropriately incorporate remaining valid work from existing plan
- [ ] Review new Roadmap and add any additional tasks
- [ ] Review w/EDX
- [ ] Review w/DC

**Comment by RachelF** [comment]
Ana, Peter, Rachel will chat on 6/22 to prep for a meeting w/Beth K on next steps for this work. Meeting w/Beth 6/30.

**Comment by RachelF** [comment]
OBE - GSA IT is now leading this work; closing
