### ISSUE TITLE
Is it better to have a stand-alone domain or be a part of a larger site?

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#406]
## Summary

When speaking with some website managers, there is a reluctance to migrate into a larger website property such as gsa.gov, digital.gov, buy.gsa.gov due to a perceived notion that their content will be harder to find. One such example (using simpler terms) was that content living at gsa.gov/green-procurement/* is harder to find than greenprocurement.gov/.

## Checklist

List below the specific actions to be taken

- [ ] Research and determine if there is anything to these arguments? 
  - [ ] Look for sites/ content that overlap. Are there differences to how traffic arrives at the site and subsequently behaves?
  - [ ] Are there SEO, Performance, and Accessibility differences between the overlapping sites per Lighthouse?
  - [ ] How do the tech stacks differ?
- [ ] Are there cost differences?
- [ ] If so, are there steps that can be taken by the larger web properties to eliminate or mitigate these issues. If not, is there data or examples that we can provide which helps make our case for consolidation?

**Comment by AKM399** [comment]
reference to #394 as a possible structure persona.gsa.gov/purpose
or verb.gsa.gov/noun

What is a target URL structure by both usability and seo standards?

**Comment by anatecture** [comment]
This is part of a larger idea: a true design system for GSA would be an inter-team collaboration: 
        1. OSC
        2. USWDS team
        3. Service Design
        4. GSA IT

**Comment by mvogelgesang** [comment]
Example outputs for gsa.gov/technology/technology-products-services/it-hardware. Results show that less than 1% of users are reaching the page via standard menu navigation on gsa.gov. 3% are using search capabilities within gsa.gov to find the content. >60% are using search engines to arrive.

|Rank|Full Referrer|Pageviews|Unique Pageviews|Avg. Time on Page|Entrances|
|----|-------------|---------|----------------|----------------|----------|
|1|google|7,317(48.27%)|6,286(47.26%)|00:01:24|4,553(45.50%)|
|2|ttd|2,997(19.77%)|2,817(21.18%)|00:04:04|2,816(28.14%)|
|3|bing|2,546(16.80%)|2,309(17.36%)|00:01:03|2,072(20.71%)|
|4|(direct)|530(3.50%)|441(3.32%)|00:01:07|112(1.12%)|
|5|search.gsa.gov/|486(3.21%)|398(2.99%)|00:01:29|202(2.02%)|
|6|gsa.gov/technology/technology-products-services/it-hardware|411(2.71%)|299(2.25%)|00:00:42|16(0.16%)|
|7|linkedin|107(0.71%)|102(0.77%)|00:00:27|102(1.02%)|
|8|gsa.gov/|73(0.48%)|65(0.49%)|00:00:45|0(0.00%)|
|9|yahoo|64(0.42%)|60(0.45%)|00:00:52|44(0.44%)|
|10|duckduckgo|60(0.40%)|55(0.41%)|00:00:54|23(0.23%)|

**Comment by mvogelgesang** [comment]
Potentially a project to engage OPM Lab on. What are the barriers (going both ways) that make it hard to incorporate certain sites as a part of a larger domain? Thinking of technical, contractual, process, color of money, etc

**Comment by mvogelgesang** [comment]
@AKM399 I see this issue as a sub-component of #625 and have updated the issues accordingly

**Comment by AKM399** [comment]
closed due to primary issue being closed
