### ISSUE TITLE
FY23 Scanning Metrics

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#451]
## Summary

Putting together a preliminary list of potential scanning items for FY23 to drive further maturation of GSA's web presence.

## Ideas

- [ ] Adoption of DAP using GA4 (possibly a best fit for Site Scanner)
- [ ] #250 - work with teams to ensure content is present in search results that describe the page or site
- [x] #557 
- [ ] robots.txt evaluation- could be tied to #250 
- [x] #601 
- [ ] Encourage adoption of JSON-LD for specific content types across GSA's sites so as to provide richer results in search and make it easier for users to find information. https://schema.org/docs/schemas.html
- [ ] Mobile friendliness
- [ ] Utilization of Google Search Console/ Bing Webmaster Tools - while this can be done on a site by site basis, we can also set it up at the top level domain. Having access to this information across all sites could help GSA better wrap their arms around the existing websites. Generally speaking, ensuring website teams have access to these reports would be valuable. Checking for this can be done by a combination of evaluating <meta> tags and examining TXT records set against the DNS
- [ ] Evaluation of web stack being less concerned about underlying databases / services and more interested in whether the site is using Drupal, Wordpress, Jekyll. Which version they are using. Is there a way to highlight sites on out of date versions or versions that are no longer actively maintained? 
- [ ] Is the site employing a CDN?
- [ ] Does site resolve or properly redirect when going to the base url (e.g. gsa.gov, something.cio.gov). We have some sites which result in a 404 or other error if you do not go to the specific starting location. 
- [ ] Similar to above, do sites properly redirect/ resolve when going to www.sitename.gov and sitename.gov? 
- [ ] Does the site contain a sitemap.xml?
- [ ] Tying sites to personas
- [ ] Additional USWDS component adoption on homepage
- [ ] Removing CUI Banners that are not needed. Driving adoption towards simpler practices when it comes to accepting warnings.
- [ ] color blindness evaluation 
- [ ] Move beyond homepage and evaluate top content/ tasks 
- [ ] Does the site contain keyword metadata (appropriate to type/subject of site)?
- [ ] Does the site use relevant keywords in page titles/headings?
- [ ] Is site associated with appropriate personas in Touchpoints?
- [ ] Does the site use modern image formats (WebP) to promote speedy page load times?
- [ ] 

## Checklist

List below the specific actions to be taken

- [ ] item 1
- [ ] item 2

**Comment by RachelF** [comment]
added a couple more items to the list :)

**Comment by AKM399** [comment]
@AKM399 to discuss GSA DAP goals for same purpose

**Comment by AKM399** [comment]
key DAP question for fy 23, analytics that indicate whether or not a bounce rate in line with design

**Comment by AKM399** [comment]
to be chunked out.  Exists as an EPIC for refinement of scan.

**Comment by AKM399** [comment]
potential for crit

**Comment by AKM399** [comment]
@hursey013

**Comment by AKM399** [comment]
@hatfieldjm4 link to your fall project?

**Comment by anatecture** [comment]
Will share w/ cloud pages team in upcoming meeting as some ideas for ways to scan for signals. @RachelF @anatecture

**Comment by anatecture** [comment]
Automation potential: 

- [ ] robots.txt evaluation- could be tied to #250 
- [ ] Is the site employing a CDN?
- [ ] Does the site contain keyword metadata (appropriate to type/subject of site)?
- [ ] Does the site use relevant keywords in page titles/headings?
- [ ] Does site resolve or properly redirect when going to the base url (e.g. gsa.gov, something.cio.gov). We have some sites which result in a 404 or other error if you do not go to the specific starting location.
- [ ] Similar to above, do sites properly redirect/ resolve when going to [www.sitename.gov](http://www.sitename.gov/) and sitename.gov?
- [ ] Additional USWDS component adoption on homepage

We have done a lot of work to address *_Move beyond homepage and evaluate top content/ tasks_* with the service category work.

**Comment by anatecture** [comment]
OBE
