### ISSUE TITLE
Improve measurement criteria - DLP Management Checklist

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#553]
### What this is
Establish objective metrics for items in the DLP Management Checklist, to help GSA web managers understand what "done" looks like when trying to comply with vaguely-worded web policy.
### Why we're tackling this
Federal web policies, laws, and regulations are notoriously vague, and don't often provide concrete examples for what compliance actually looks like. This project is an effort to establish clear criteria and provide easy-to-use guidance to help GSA web teams understand how to meet policy requirements in a tangible, actionable way.
### How we'll do it
Select three to five (3-5) policy items from the DLP Management Checklist and work with SMEs to identify clear measurement criteria, and provide guidance on how to meet the criteria.

## Additional context and links

[DLP-MANAGEMENT Checklist for GSA Websites](https://docs.google.com/spreadsheets/d/1o_NMWBbbOpeKvAmLOLTGHbk3ldOeyO3g1SKb-EP5ZWs/edit#gid=1232597517)

## Checklist

- [x] review [2021 Capacity Assessment](https://docs.google.com/spreadsheets/d/18dbV0CV1b-vi_aSvBYJZfCAr3MfMyTXWiQYtdb4c0yA/edit#gid=2135783770) (maturity self-eval used by HISPs) to see if it could be helpful
- [x] Identify several policy areas on which to focus; avoid policy areas such as 508 that other parts of GSA are already working to improve ([draft list](https://docs.google.com/document/d/1afkegSFTfePwVTMIQTU26fhYMAdYfJIiMtOcdDfnBiE/edit#))
- [x] Draft proposed measurement criteria 
- [x] Share with EDX team for input/feedback
- [x] Identify SMEs
- [ ] Interview SMEs to determine how best to measure things in the selected categories/policy areas
- [ ] Align criteria w/GSA performance goals
- [ ] Update DLP Management checklist

**Comment by anatecture** [comment]
[Measurement criteria](https://docs.google.com/document/d/1afkegSFTfePwVTMIQTU26fhYMAdYfJIiMtOcdDfnBiE/edit#heading=h.2iumpjr5qrc) for review

**Comment by RachelF** [comment]
Updated guidance on "trust" policy category to streamline and clarify how to meet the reqs. 
[Updated Trust criteria](https://docs.google.com/spreadsheets/d/1vbiWkystd7ePa4LZ-XhbGI0Oxu_jOQvfvfk_PMd_-cQ/edit#gid=1374342162)
Next step: Ana and Liz will test w/users during FY23 Q2.
