### ISSUE TITLE
Edit sites in Touchpoints that have "stage" or "staging" in their DNS name

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#626]
There are currently 9 websites in Touchpoints that have "stage" or "staging" in their DNS name but have a "production" value of "in_development". 

- [ ] Gain consensus with the EDX teamthat any site with "stage" or "staging" in its DNS should have a "production" value of "in_development"

Edit the following sites in Touchpoints to change their "production" field value from "in_development" to "staging": 
- [ ] staging.performance.gov
- [ ] federation-staging.data.gov
- [ ] sdg-staging.data.gov
- [ ] federalistapp-staging.18f.gov
- [ ] analytics-staging.app.cloud.gov
- [ ] staging.code.gov
- [ ] staging.vote.gov
- [ ] staging.d2d.gsa.gov
- [ ] staging.pulse.cio.gov
