### ISSUE TITLE
January update to websites digital taxonomy

### ISSUE THREAD

**Issue by hatfieldjm4** [GSA/EDX#661]
Update the authoritative source sheet for any new public-facing websites on Touchpoints. 

- [ ] First begin by recording the first topics that come to mind when visiting the new site in [column E of this spreadsheet](https://docs.google.com/spreadsheets/d/1FdX7Jtz8I96R87TnTlkOgs5plXMuq2Z9-bo0Vx2HIOU/edit#gid=431930911).
- [ ] After doing so, extract some common key words from your verbose description of the site and update the [authoritative source sheet](https://docs.google.com/spreadsheets/d/1dY-k0ULWhuPLAMLDdRXybgY4GoWBPki3UWUmjFWLrEc/edit#gid=0). 
- [ ] If any new key words are created as a result, ensure that they are defined in the [definitions tab](https://docs.google.com/spreadsheets/d/1dY-k0ULWhuPLAMLDdRXybgY4GoWBPki3UWUmjFWLrEc/edit#gid=329719329).

**Comment by AKM399** [comment]
@hatfieldjm4 i believe this has been done?
