### ISSUE TITLE
Content Delivery - Rachel's Spring 2023 Project

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#672]
## Summary
Spring 2023 project to improve OCE content offerings across GSA, particularly on Digital.gov and InSite, including DLP checklist content.

## Additional context and links
[Content Delivery Project Plan](https://docs.google.com/document/d/1XKwOv3nNZSB9hTrT_m7JhO_RazWLNmZ6AyWWPSlzZ0w/edit#)

## Project Checklist
- [x] Develop project plan
- [x] Review with Ana
- [x] Document [in-process content work for InSite](https://github.com/GSA/EDX/issues/640)
- [x] Document [content collaborations with Digital.gov](https://github.com/GSA/EDX/issues/680)
- [x] Track work to [publish HCD Guides](https://github.com/GSA/EDX/issues/551)
- [x] Track work to [repurpose CX Guide content](https://github.com/GSA/EDX/issues/681)
- [x] Create Issues for each landing page project 

## Landing pages
- [x] [Trust](https://github.com/GSA/EDX/issues/676) - early Feb
- [x] [Design/UX](https://github.com/GSA/EDX/issues/677) - late Feb
- [x] [Content](https://github.com/GSA/EDX/issues/678) - late March
- [x] [Accessibility](https://github.com/GSA/EDX/issues/679) - June

## Update Launch and Management checklists
- [x] Organize policy reqs so related items are groups together
- [x] Develop how-to guidance for each group of policy reqs
- [x] Identify SMEs to help review
- [x] Reach out to SMEs to enlist their help
- [x] Hold an office hours session to answer questions
- [x] Set a date for feedback
- [x] Share w/DC and ask for their feedback
- [x] Incorporate SME and DC feedback
- [x] Update DLP page w/links to V2 checklists
- [x] Develop comms to clarify L5 perf goal reqs for WMs
- [x] Communicate to WMs on checklist requirements

**Comment by RachelF** [comment]
Adding a running list of additional in-process Digital.gov content projects here:

***10 Questions article***
- [ ] [draft content](https://docs.google.com/document/d/1VvAy4o-kymOA_Kz-Qj0gDVsEUc3D9a3TDeWJLJww088/edit#)
- [ ] submit for publication
- [ ] published

***Digital governance article***
- [ ] [draft content](https://docs.google.com/document/d/12pcGe85PXUkgDm4EZDT-1wbmiSxTA2gGZN7Df6LsMLk/edit#)
- [ ] submit for publication
- [ ] published

***Website Manager article***
- [ ] [draft content](https://docs.google.com/document/d/1sB72avoigmJi16oXte4BJ-n6l9YlE1h71lANTQNrJ2g/edit)
- [ ] complete internal editorial review
- [ ] submit for publication
- [ ] published

**Comment by anatecture** [comment]
this is great! what's the one sprint you're planning for early april before PTO?

**Comment by RachelF** [comment]
@anatecture 4 months=4 landing pages. There are add'l content projects sprinkled in there throughout (one-off articles for DG, CX Guide, HCD Guides, InSite) so it's a steady stream of at least one deliverable every 2 weeks.

**Comment by RachelF** [comment]
Shifted schedule a bit to incorporate DLP checklist work and accommodate for staffing shifts.

**Comment by RachelF** [comment]
Accessibility page has been drafted and is with 508 team for SME review

**Comment by RachelF** [comment]
4 policy pages identified here have been submitted to Digital.gov; GSA checklists updated
