### ISSUE TITLE
Multi site Manager EPIC - Mike Chipman

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#684]
Website Evaluation - Mike Chipman

- [x] #646 
- [x] #645 
- [x] #644 
- [x] #643 
- [x] #642 
- [x] #641 

- [ ] [Interview Notes](https://docs.google.com/document/d/1ZRgBrOZxJljLSPUkkUHhlKWOdvhfHrIL5hg5o_TnBn4/edit?usp=sharing)
- [ ] [coding](https://docs.google.com/spreadsheets/d/1XrzNF9Mvquh7zh-0HWErTaH1YY1nbbenI6ANN7jVetE/edit?usp=share_link)
- [ ] [digital registry information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=H266)
