### ISSUE TITLE
Multi site Manager EPIC - Doug Dubois

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#688]
- [ ] #648 - Michael Cooper
- [x] #649 
- [ ] #650 - Kehinde Odebo
- [ ] #651  - KehindeOdebo
- [ ] #652  - Kehinde Odebo

- [x] [Coding](https://docs.google.com/spreadsheets/d/1l6k8ITrEcSCiPRttjohT0FbQ5uY1ZynYdaDEsTGTYtY/edit?usp=share_link)
- [x] [Interview](https://docs.google.com/document/d/1ci2F2OAkcUGLcvMwJQU9eIUwzwPp26Tuzzilr8DflGc/edit?usp=share_link)
- [x] [digital registry information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=H121)

**Comment by RachelF** [comment]
Doug only manages eLibrary; interviewed today
