### ISSUE TITLE
Multi Site Manager EPIC - Christy Hermanson

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#689]
- [x] #653 
- [x] #654 
- [x] #655 
- [x] #656 

- [ ] [Coding](https://docs.google.com/spreadsheets/d/11BVlybpPMpOyfPoi0yiP4cBXqvducCETgstldA4RQuI/edit?usp=share_link)
- [ ] [interview](https://docs.google.com/document/d/1BGJJU5V0yfXxcPFlKsgucLYv7zitIFEa0JBRi8oei0s/edit?usp=share_link)
- [ ] [Registry information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=G55)
