### ISSUE TITLE
Multi site Manager EPIC - Lloyd Aucoin

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#690]
- [x] ~~#657 evaluation sprint 1~~ (realestatesales.gov is managed by someone else and will be rescheduled.)
- [x] #658 evaluation sprint 1
- [x] #691 evaluation sprint 2
- [x] #692 evaluation sprint 2

- [x] [Interview](https://docs.google.com/document/d/1mf8AR2SgsUHhgndFg2iITffqsk5Za6WNaXiBzu38lNM/edit?usp=share_link)
- [x] [Coding ](https://docs.google.com/spreadsheets/d/1dWXwoB9XdECF0m54IuqPH6S7klpWIUZgnufT5IlN_MM/edit?usp=share_link)
- [x] [registry information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=H247)

**Comment by RachelF** [comment]
Interview completed today on gsaxcess.gov, gsaxcesspractice.fas.gsa.gov, and mysales.fas.gsa.gov. 
realestatesales.gov is managed by someone else and will be rescheduled.

**Comment by RachelF** [comment]
findings report drafted, tagged @hatfieldjm4 for review

**Comment by hatfieldjm4** [comment]
Review complete.
