### ISSUE TITLE
implement search engine result screenshots

### ISSUE THREAD

**Issue by mvogelgesang** [GSA/EDX#693]
Utilize the existing screenshot module and adapt to also support search engine screenshots.

### Tasks
- [x] determine steps required for puppeteer
- [x] develop naming convention for files
- [x] add to output json file
- [x] implement
