### ISSUE TITLE
Multi site Manager EPIC - Ammie Farraj Feijoo

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#696]
- [x] #695 
- [x] #694 

- [x] [Interview ](https://docs.google.com/document/d/1TVPc3y8EOJs37lwm6DkNXDUz2xlLYzYHaRCc_HQ47AI/edit?usp=share_link)
- [x] [Interview Coding](https://docs.google.com/spreadsheets/d/1rTmyulSrN4fLNVbMzIa7dZoYvUcYsBm2GglqpBlywxs/edit?usp=share_link)
- [x] [Digital Registry Information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=H12)

**Comment by RachelF** [comment]
Interview complete 2/1/2023 by Rachel & Jonah.
@AKM399 see notes doc for some comments/feedback on the interview questions.
@RachelF drafted updates to the resources section of the findings template, including addition of a link to the DLP.

**Comment by RachelF** [comment]
report drafted, tagged @hatfieldjm4 for review
