### ISSUE TITLE
Multi Site Manager EPIC - Julia Elman

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#700]
- [ ] #697

- [ ] #698 

- [ ] #699

- [ ] [Interview](https://docs.google.com/document/d/1_2RjtEGw3caS0ccGgo8tlmjuyZh2Erh8-1D_IXj7SMQ/edit?usp=share_link)
- [ ] [Interview Coding](https://docs.google.com/spreadsheets/d/1nrtl9k8W3TS2kI8qTcfgkg0Nux36DCjgm2bibwryiqo/edit?usp=share_link)
- [ ] [Digital Registry Information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=H192)
