### ISSUE TITLE
multi site manager EPIC - Hyon Kim

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#703]
- [x] #701 
- [x] #702 

- [ ] [ Interview](https://docs.google.com/document/d/1S8M7VzuNjt6934bTQEmTwMSuzVMvLQbrGpef3dXQU0k/edit?usp=share_link)
- [ ]  [Interview Coding](https://docs.google.com/spreadsheets/d/1_CtN5RFrr5eyxnGscWnf4b6k2ESbSFhDtHnxS-hg0Pw/edit?usp=share_link)
- [ ]  [Registry information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=H158)
