### ISSUE TITLE
Multi site Manager EPIC - John Jideny

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#713]
- [ ] #712 
- [ ] #711 

- [ ] [Interview](https://docs.google.com/document/d/18izxz3N2Gz5seJXjd-LqUdroaM9Fmp0fxUoOZ1NUs64/edit?usp=share_link)
- [ ] [Interview Coding](https://docs.google.com/spreadsheets/d/1c2dX9SUOTfqz_zOkNcjAsmbfKe8XM8I8hfZIGg1HEzU/edit?usp=share_link)
- [ ] [Digital Registry Information](https://docs.google.com/spreadsheets/d/1e95psJbKn32xIcvXVojvh03EO7xMImlJ4lARVO5t1HU/edit#gid=644883864&range=H187)

**Comment by RachelF** [comment]
report drafted, tagged @hatfieldjm4 for review

**Comment by hatfieldjm4** [comment]
Review complete.
