### ISSUE TITLE
Follow up on new website registrations - February 2023

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#719]
## Summary

Sites that have been added to Digital Registry and need follow-up w/WMs, to prompt them to submit a proposal request

## Additional context and links
Past registrations documented here https://github.com/GSA/EDX/issues/629
Includes asap.gsa.gov, calm.gsa.gov, collab.gov, fac.gov, workplace.gsa.gov, pidatacollection.paymentaccuracy.gov

## Sites 
- [x] eis-public-pricer.eos.gsa.gov - Mark V added; reached out to Brad/Jaime to track down the site manager
- [x] catalog.gsa.gov - AM emailed benjamin.murphy@gsa.gov on 2/2
- [x] msa-pub.gsa.gov - RF emailed gregg.rovinsky@gsa.gov 2/3
- [x]  fleet.gov - NOT live; need to follow up with [jamie.lindabury@gsa.gov](mailto:jamie.lindabury@gsa.gov), FAS about DLP (submitted as an application)
- [x]  piv.golearnportal.gov - needs follow-up about DLP and requirement to host site on .gov - Comment from Ryan W in Touchpoint states "The site is actually: https://piv.golearnportal.org/ Alison Kohler pointed me (Ryan) to it, Sheila Berlin and Sheila Dawson may be contacts." -- should redirect to https://piv.golearnportal.org/ -- RF emailed both Sheilas 2/3

**Comment by RachelF** [comment]
1. EIS: Brad identified the site manager so I added him to the registry record and asked Brad to have him update the site info. Changed the site record to production status since the site is live.
2. PIV: Talked w/Sheila Dawson who confirmed that they do not need a .gov front-end for the training portal (which actually lives at piv.golearnportal.net). Delete the record from the registry.

**Comment by djharrity** [comment]
Re: PIV -- is that recommendation prior to the release of the new OMB Memo M-23-10, The Registration and Use of .gov Domains in the Federal Government, dated 8 Feb 2023.

**Comment by RachelF** [comment]
@djharrity Yes the convo happened before the new memo was issued. What are your thoughts/recommendations on how best to handle situations like with (training portal operated under contract by a 3rd party vendor, in partnership w/another agency)?
@anatecture @mvogelgesang for awareness

**Comment by mvogelgesang** [comment]
@RachelF there was a previous OMB memo focused on .gov domains issued during the Obama administration. [Policies for Dot Gov Domain Issuance for Federal Agency ... ](https://obamawhitehouse.archives.gov/sites/default/files/omb/egov/memo/policies-for-dot-gov-domain-issuance-for-federal-agency-public-websites.pdf) which I thought put a nail in this whole thing. The more recent memo, [M-23-10](https://www.whitehouse.gov/wp-content/uploads/2023/02/M-23-10-DOTGOV-Act-Guidance.pdf) further clarifies the point. This learning site does not seem to fall under the categories listed as exceptions.

**Comment by djharrity** [comment]
> @djharrity Yes the convo happened before the new memo was issued. What are your thoughts/recommendations on how best to handle situations like with (training portal operated under contract by a 3rd party vendor, in partnership w/another agency)? @anatecture @mvogelgesang for awareness

USA Learning (aka, usalearning.net) and golearning.org is an interesting use case, but I would agree with @mvogelgesang in that it does not seem to fall under the exception categories.  It might, if other non-governmental entities used usalearning.net or golearning.org - but each use case appears to be government/military related. 

https://piv.golearnportal.org/ = GSA PIV Training 
https://totalforcevlc.golearnportal.org/ = DOD Total Force Learning Center

https://golearn.usalearning.net/ = Go Learn Training (Home)
https://usastaffingtest.usalearning.net/ = USA Staffing Training
https://olenmfs.usalearning.net/ = NOAA Office of Law Enforcement Virtual Training Center
https://achp.golearnportal.org/ = Advisory Council on Historic Preservation (ACHP)

Yet, GoLearning/USALearning supports numerous examples of {{subdomain}}.usalearning.gov}} sites to include:
https://cdse.usalearning.gov/ = STEPP Learning Portal (of DoD's DCSA)  
https://securityawareness.usalearning.gov/ = also part of DoD's DCSA 
https://fedvte.usalearning.gov/ = Federal Virtual Training Environment 
https://dhscareermapping.usalearning.gov/ = DHS Career Mapping
https://tsacareermap.usalearning.gov/ = TSA Career Mapping  
https://afm.fmi.gov/ = Accelerate FM (GSA's online training portal for federal buildings personnel)

**Comment by AKM399** [comment]
@RachelF can we close?

**Comment by AKM399** [comment]
@RachelF closable?

**Comment by RachelF** [comment]
fleet.gov is now live as https://fleet.gsa.gov/fleetportal/
