### ISSUE TITLE
tracking the status of website manager interviews that need rescheduling

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#770]
- [x] Alyssa Galik - oes.gsa.gov - was supposed to be 3/3 needs a new manager named.  reached out to pompa
- [x] tony butcher - fairs.reporting.gov and reporting.gov - was supposed to be 3/2 needs a new manager named.  reached out to Christopher Freeman
- [x] gsac0.fas.gsa.gov - actual manager is Don Ostrolencki, needs rescheduling
- [ ] gsaglobalsupply.gsa.gov actual manager might be michael cooper?  needs rescheduling
- [x] open.gsa.gov - needs rescheduling with new website managers with rose lanzano - who doesnt' claim it
- [x] gsbca.gsa.gov - arthur hawkins unresponsive.  consult with @gailsprinkle - not pursuing
- [x] tmf.cio.gov - needs new manager named
- [ ] designsystem.sam.gov - if they dont shut down by may
- [x] analytics.usa.gov - unknown manager

**Comment by AKM399** [comment]
@gailsprinkle -  alyssa galik has gone to state, new manager is amanda girard, and is now scheduled

**Comment by AKM399** [comment]
@gailsprinkle fairs.reporting.gov is now Tim Fulk, still tracking down reporting.gov, have an email out to peter nguyen about it.

**Comment by AKM399** [comment]
@gailsprinkle Gsaco0 is Don Ostralencki, its now scheduled

**Comment by AKM399** [comment]
analytics.usa.gov - talking to phil ashlock
open.gsa.gov - new cconversation with billy wales

**Comment by AKM399** [comment]
tmf.cio.gov needs to be replaced - not a gsa site.  @RachelF should we reach out to get them to change the contact email which is gsa?

**Comment by RachelF** [comment]
@AKM399 per OGP, TMF is an external website, but it's giving a cert error right now and won't load so I can't verify whether or not there is still any GSA branding on the site. We need to contact the TMF PMO and work w/them to remove GSA branding; them we can reclassify as external and remove from our interview list.

**Comment by AKM399** [comment]
The only branding I recall is in the contact email, its a gsa.gov address.

U.S. General Services Administration

*Aaron Meyers*

Office of Customer Experience

Service Design Program

1800 F Street, NW

Washington, DC 20405

Mobile:  202-679-5718
