### ISSUE TITLE
Decommission feedback.usa.gov

### ISSUE THREAD

**Issue by ryanwoldatwork** [GSA/EDX#776]
## Goal

Decommission feedback.usa.gov

## Tasks

* [x] Review Decommissioning flowchart
* [x] Submit EDX form
* [ ] Consult with Records Management
* [ ] Notify GSA/TTS Digital Council
* [ ] Move/redirect/remove contact
* [ ] Sunset DNS
* [ ] Remove the Website from Touchpoints inventory

**Comment by ryanwoldatwork** [comment]
cc @RachelF

**Comment by AKM399** [comment]
@anatecture has touched base on this one

**Comment by AKM399** [comment]
@ryanwoldatwork is this site still targeted to go?

**Comment by ryanwoldatwork** [comment]
@AKM399 - yep

**Comment by AKM399** [comment]
to work with @beharti

**Comment by AKM399** [comment]
site closed
