### ISSUE TITLE
Decommissioning tracker

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#807]
track websites that discovery shows could be decommissioning:

SIte - evaluation - target date

- [x] wdolhome.sam.gov #656 
- [x] fbohome.sam.gov #653
- [ ] catalog.data.gov #220 
- [ ] mysales.fas.gsa.gov #658  
- [ ] drivethru.gsa.gov #258 
- [x] labs.gsa.gov - thanks @mvogelgesang !!

**Comment by beharti** [comment]
TTS - Decommissioning references identify sites, and GitHub pages with additional technical instructions.  [https://docs.google.com/spreadsheets/d/1EGgQpwq8kc43TuTYxtQAhzEnhf_p7m_6T0Q8Dt9mqjo/edit#gid=1311804654](url)

**Comment by AKM399** [comment]
@AKM399 put a is it decommissioning code in website evaluations

**Comment by beharti** [comment]
Competing definitions/reference to “decommissioning” - retired, rebranded, redirected, consolidated and shutting down? which made some conversations a challenge to commit to the terms defining whether a site is “officially decommissioning”,  thus impacting how we do the process and document the steps.
