### ISSUE TITLE
FY24 M-23-22 training series

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#966]
## FY24 training series on M-23-22
Partner with CASE and GSA DX Lead to develop and present a series of trainings for the Digital CoP about the OMB guidance on 21st Century IDEA.

## Sessions
March - Intro to M-23-22
May - Accessibility
July - PDFs
September - Content cleanup

## To-Do
- [ ] Engage CASE to expand this to include Digital CoP
- [ ] Confirm session topics for FY24
- [ ] Prep for first session
- [ ] Conduct first session
- [ ] Prep for second session
- [ ] Conduct second session
- [ ] Prep for third session
- [ ] Conduct third session
- [ ] Prep for fourth session
- [ ] Conduct fourth session
