### ISSUE TITLE
2024 Website self-assessments

### ISSUE THREAD

**Issue by RachelF** [GSA/EDX#989]
## 2024 Website self-assessments
Develop and disseminate guidance to GSA WMs about completing the [DLP Website Self-Assessment Checklist](https://docs.google.com/spreadsheets/d/1TTls336uHnsWICT3Yrsz0Sq327kNc9vQQ1t-CQjdYUc/edit?usp=drive_link).
Determine how best to gather and analyze submissions, and sythesize and share findings.
Required in 2024 SES performance plans.

## To-do list
- [ ] Update checklist to incorporate the latest OMB policies
- [ ] determine process for teams to submit their completed checklist
- [ ] draft the guidance email
- [ ] determine who will send
- [ ] complete any prep work needed to accept checklist submissions
- [ ] finalize email
- [ ] send email
- [ ] send reminder email for those who haven't submitted by mid-Sept
- [ ] analyze submissions to find trends, high- and low-lights
